name: Deploy project
on: workflow_dispatch
jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install 
      - name: Run lint
        run: npm run lint
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install 
      - name: Run tests
        run: npm run test
  build:
    name: Build project
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install 
      - name: Run tests
        run: npm run build
  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy project
        run: echo "Deploying ... " 
