name: Deploy project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install 
      - name: Run lint
        run: npm run lint